package br.com.sifcon.nfs.exception;

public enum NfsErrorCode {
	A1("A1", "Alguns dos dados informados não constam do cadastro do contribuinte.", "O tipo do serviço prestado não está registrado no cadastro do contribuinte. Procure a Prefeitura para registrar os códigos de tributação, códigos de serviço, códigos da subclasse CNAE ou o item da lista da Lei Complementar correspondentes aos serviços pre"),
	A10("A10", "Inscrição municipal do prestador de serviço encontra-se paralisada ou cancelada ou desativada ou baixada.", "A NFS-e foi gerada e o prestador de serviço deverá comparecer à Prefeitura para regularizar sua situação."),
	A11("A11", "NFS-e emitida com falta de elementos de qualificação do prestador do serviço.", "NFS-e foi gerada e o prestador de serviço deverá comparecer à Prefeitura para regularizar sua situação."),
	A12("A12", "RPS em duplicata no lote foram ignorados.", "A Prefeitura desconsiderou os RPS cujos elementos eram idênticos aos elementos de RPS já processados."),
	A13("A13", "Prazo para a conversão do RPS em NFS-e vencido", "Procure a Prefeitura para regularizar a situação."),
	A14("A14", "O campo ValorISS informado indevidamente.", "O valor do ISSQN é calculado pela Prefeitura e não pode ser informado pelo contribuinte. O valor informado foi desconsiderado."),
	A15("A15", "Alíquota informada indevidamente.", "A alíquota utilizada para a determinação do valor do ISSQN é determinada pela Prefeitura. Não deve ser informada pelo contribuinte. A alíquota informada foi desconsiderada."),
	A16("A16", "Código da subclasse CNAE informado indevidamente.", "O código da subclasse CNAE correspondente ao serviço prestado não é utilizado pela Prefeitura. O elemento informado foi desconsiderado."),
	A17("A17", "Não informe inscrição municipal quando o intermediário do serviço for domiciliado em outro município.", "Inscrição municipal do intermediário desconsiderada."),
	A18("A18", "O tipo de serviço informado não permite indicação de código da obra.", "Código da obra desconsiderado."),
	A19("A19", "O tipo de serviço informado não permite indicação de ART - Anotação de Responsabilidade Técnica.", "ART - Anotação de Responsabilidade Técnica desconsiderada."),
	A2("A2", "Valor das deduções indevido.", "A NFS-e foi emitida considerando a informação do RPS, no entanto o tipo de serviço prestado, identificado pelo código de tributação, código se serviço, código da subclasse CNAE ou item da lista da Lei Complementar, não permite dedução da base de cálculo d"),
	A20("A20", "O regime de tributação informado difere do registrado na Prefeitura.", "A NFS-e foi emitida considerando o regime de tributação informado. Procure a Prefeitura para atualizar o regime de tributação no cadastro do contribuinte."),
	A21("A21", "Opção pelo SIMPLES Nacional não consta do cadastro do contribuinte.", "Não há registro no cadastro do contribuinte de opção pelo SIMPLES Nacional. A NFS-e foi emitida considerando a informação do RPS. Procure a Prefeitura para regularizar a situação."),
	A22("A22", "Código de tributação incompatível com o município de incidência do ISSQN.", "A NFS-e foi emitida considerando a informação do RPS, no entanto o código de tributação informado não permite a tributação em outro município. Consulte na legislação  o local de incidência do ISSQN."),
	A23("A23", "O prestador do serviço não possui incentivo fiscal no cadastro da Prefeitura.", "Não há concessão de incentivo para o prestador de serviço registrada na Prefeitura. A NFS-e foi emitida considerando a informação do RPS. Procure a Prefeitura para regularizar a situação."),
	A24("A24", "País da prestação do serviço indevido.", "O código do país da prestação do serviço somente deverá ser informado quando  a exigibilidade do ISSQN for igual a <Exportação>."),
	A25("A25", "País do tomador do serviço indevido.", "O código do país do tomador do serviço somente deverá ser informado quando  o município do tomador do serviço for igual a <9999999>."),
	A26("A26", "E-mail do tomador do serviços inválido.", "O e-mail do tomador de serviços não é válido e foi  desconsiderado."),
	A27("A27", "CEP do logradouro do tomador do serviço inexistente.", "A NFS-e foi emitida com o CEP do tomador do serviço informado no RPS."),
	A28("A28", "Inscrição municipal do tomador do serviço indevida.", "Não informe o campo inscrição municipal do tomador do serviço quando este for do exterior."),
	A29("A29", "CNPJ/CPF do tomador do serviço indevida.", "Não informe o campo CNPJ/CPF do tomador do serviço quando este for do exterior."),
	A30("A30", "RPS possui campo(s) informado(s) que não é (são) adotado(s) pelo município", "Algum campo não obrigatório no Termo de Referência informado no RPS não é adotado pelo município. Por este motivo, não foi consistido e nem será considerado como informação válida para a NFS-e."),
	A5("A5", "Endereço do tomador do serviço difere do constante na base de dados do município.", "A NFS-e foi emitida considerando o endereço do tomador do serviço informado no RPS."),
	A6("A6", "Inscrição municipal do tomador não encontrada.", "A inscrição municipal do tomador do serviço informada no RPS não está registrada na Prefeitura. A NFS-e foi emitida considerando que o tomador do serviço não está inscrito na Prefeitura."),
	A7("A7", "A inscrição municipal do tomador do serviço está paralisada ou cancelada ou desativada ou baixada.", "A inscrição municipal do tomador do serviço informada no RPS está paralisada ou cancelada ou desativada ou baixada no cadastro municipal. A NFS-e foi emitida considerando que o tomador do serviço não está inscrito na Prefeitura."),
	A8("A8", "E-mail do tomador do serviço inválido.", "O e-mail do tomador de serviços não é válido e foi ignorado. Não será enviado e-mail de confirmação da emissão da NFS-e para o tomador do serviço."),
	A9("A9", "Inscrição municipal incorreta.", "A NFS-e foi gerada considerando a inscrição municipal vinculada ao CNPJ/CPF informado."),
	E10("E10", "RPS já informado.", "Para essa Inscrição Municipal/CNPJ já existe um RPS informado com o mesmo número, série e tipo."),
	E100("E100", "Valor dos serviços inválido.", "O campo valor dos serviços é numérico e deverá ter tamanho máximo de 15 números inteiros e dois decimais."),
	E101("E101", "Valor das deduções inválido.", "O campo valor das deduções é numérico e deverá ter tamanho máximo de 15 números inteiros e dois decimais."),
	E102("E102", "Valor dos descontos inválido.", "O campo valor dos descontos é numérico e deverá ter tamanho máximo de 15 números inteiros e dois decimais."),
	E103("E103", "Valor da Retenção de tributo federal inválida.", "O campo referente a retenção de tributo federal é numérico e deverá ter tamanho máximo de 15 números inteiros e dois decimais."),
	E104("E104", "Item da lista inválido.", "O campo item da lista de serviço deverá ter tamanho máximo de 5 caracteres."),
	E105("E105", "Código CNAE inválido.", "Utilize sete caracteres para informar o código da subclasse CNAE correspondente ao serviço prestado."),
	E106("E106", "Código de tributação inválido.", "Utilize no máximo 20 caracteres para informar o código do serviço prestado."),
	E107("E107", "Discriminação do serviço inválida.", "Utilize no máximo 2000 caracteres para descrever o serviço prestado."),
	E11("E11", "Número do RPS não informado.", "Informe o número do RPS."),
	E112("E112", "Inscrição Municipal do intermediário do serviço inválida.", "O campo Inscrição Municipal do intermediário do serviço é numérico e deverá ter tamanho máximo de 15 dígitos."),
	E113("E113", "Número do logradouro não informado.", "Para este tomador do serviço informe o número do logradouro."),
	E114("E114", "Bairro do tomador do serviço não informado.", "Para este tomador do serviço informe o bairro."),
	E115("E115", "UF do tomador do serviço não informada.", "Para este tomador do serviço informe a UF."),
	E117("E117", "Nome/Razão Social do tomador do serviço inválida.", "Nome/Razão Social do tomador do serviço deverá ter tamanho máximo de 115 caracteres."),
	E118("E118", "Nome/Razão Social do tomador do serviço não informado", "Para este tomador do serviço informe o Nome/Razão Social."),
	E119("E119", "Logradouro do endereço do tomador do serviço inválido.", "O campo endereço do tomador do serviço deverá ter tamanho máximo de 125 caracteres."),
	E12("E12", "Tipo do RPS  não informado.", "Informe o tipo do RPS, conforme indicado na documentação da NFS-e."),
	E120("E120", "Número do logradouro inválido.", "O campo número do endereço do tomador do serviço deverá ter tamanho máximo de 10 caracteres."),
	E121("E121", "Complemento do endereço inválido.", "O campo complemento do endereço do tomador do serviço deverá ter tamanho máximo de 60 caracteres."),
	E122("E122", "Bairro do tomador do serviço inválido.", "O campo bairro do tomador do serviço deverá ter tamanho máximo de 60 caracteres."),
	E125("E125", "CEP do tomador do serviço inválido.", "O campo CEP do tomador do serviço deverá ter tamanho máximo de 8 dígitos."),
	E126("E126", "E-mail do tomador do serviço inválido.", "O campo e-mail do tomador do serviço deverá ter tamanho máximo de 80 caracteres."),
	E127("E127", "Telefone do tomador do serviço inválido.", "Consulte o Manual da NFS-e para saber quais as regras de preenchimento do telefone do tomador do serviço."),
	E128("E128", "Razão Social do intermediário do serviço inválida.", "O campo razão social do intermediário do serviço deverá ter tamanho máximo de 115 caracteres."),
	E129("E129", "Código da obra inválido.", "O campo código da obra deverá ter tamanho máximo de 15 caracteres."),
	E130("E130", "Número da ART inválido.", "O campo ART deverá ter tamanho máximo de 15 caracteres."),
	E131("E131", "Data inicial inválida.", "A data informada deverá estar no formato DD/MM/AAAA e deve ser uma data válida."),
	E132("E132", "Data final inválida.", "A data informada deverá estar no formato DD/MM/AAAA e deve ser uma data válida."),
	E133("E133", "Data final posterior a data de hoje.", "Informe uma data final igual ou anterior a data de hoje."),
	E134("E134", "Data final anterior à data inicial.", "Informe uma data final igual ou superior a data inicial da pesquisa."),
	E135("E135", "Período consultado superior ao permitido.", "Consulte o manual da NFS-e e limite as datas inicial e final ao período permitido."),
	E136("E136", "Número da NFS-e consultada inválido.", "O campo número da NFS-e é numérico e deverá ter tamanho máximo de 15 dígitos."),
	E137("E137", "Data de emissão da NFS-e informada incorretamente.", "Informe corretamente a data da emissão da NFS-e a ser consultada."),
	E138("E138", "Usuário não autorizado a realizar o serviço.", "Informe os dados de um usuário autorizado a executar o serviço."),
	E139("E139", "Número da NFS-e a substituir inválido.", "O campo número da NFS-e substituída é numérico e deverá ter tamanho máximo de 15 dígitos."),
	E14("E14", "Data da emissão do RPS não informada.", "Informe a Data da emissão do RPS conforme indicado na documentação da NFS-e."),
	E140("E140", "Bairro do prestador do serviço inexistente", "Informe corretamente o nome bairro do prestador do serviço"),
	E141("E141", "Inscrição Municipal do prestador do serviço não informada", "informe a Inscrição Municipal do prestador do serviço"),
	E145("E145", "Regime Especial de Tributação inválido.", "Informe o regime especial de tributação utilizando dois algarismos. Consulte o Manual da NFS-e para saber quais são os regimes autorizados pela Prefeitura a utilizar NFS-e."),
	E149("E149", "CNPJ do prestador do serviço inválido", "O campo CNPJ Prestador do serviço é numérico e deverá ter tamanho máximo de 14 dígitos."),
	E15("E15", "Data da emissão do RPS inválida.", "Informe a Data da emissão do RPS conforme indicado na documentação da NFS-e."),
	E150("E150", "Série do RPS não informada", "Campo de preenchimento obrigatório, caso não utilize série, preencha o campo com 00000."),
	E151("E151", "Quantidade de RPS não informada", "Informe a quantidade de RPS contidos no lote"),
	E152("E152", "Indicador de ISSQN retido não informado.", "Informe 1 para ISSQN Retido ou 2 para ISSQN não Retido."),
	E153("E153", "Valor ISSQN retido inválido", "O campo valor do ISSQN retido é numérico e deverá ter tamanho máximo de 15 números inteiros e dois decimais."),
	E154("E154", "CNPJ/CPF do intermediário do serviço inválido.", "O campo CNPJ/CPF do Intermediário do serviço é numérico. E deverá ter tamanho de 14 dígitos para CNPJ e 11 dígitos para CPF."),
	E155("E155", "CNPJ/CPF do tomador  do serviço inválido.", "O campo CNPJ/CPF do tomador do serviço é numérico. E deverá ter tamanho de 14 dígitos para CNPJ e 11 dígitos para CPF."),
	E157("E157", "Usuário não tem autorização para solicitar o serviço.", "A pessoa física ou jurídica, identificada pelo CPF ou CNPJ, não está autorizada a solicitar o serviço para o contribuinte identificado pelo CPF ou CNPJ."),
	E158("E158", "Inscrição Municipal do prestador do serviço inválida", "O campo Inscrição Municipal do prestador do serviço é numérico e deverá ter tamanho máximo de 15 dígitos."),
	E16("E16", "A data da emissão do RPS não poderá ser superior a data de hoje.", "Informe uma data de emissão de RPS válida."),
	E160("E160", "Arquivo em desacordo com o XML Schema.", "Consulte o Manual da NFS-e para saber quais são as versões de XML Schema suportadas pelo sistema."),
	E162("E162", "Alíquota do simples nacional incorreta.", "Informe um percentual de acordo com o enquadramento na tabela de alíquota do simples nacional."),
	E163("E163", "Alíquota não informada para retenção do ISSQN no Simples Nacional", "Informe um percentual de acordo com o enquadramento na tabela de alíquota do simples nacional."),
	E164("E164", "Valor do ISSQN devido inválido.", "O campo valor do ISSQN é numérico e deverá ter tamanho máximo de 15 números inteiros e 2 decimais."),
	E165("E165", "Alíquota do serviço inválida", "Consulte o manual da NFS-e para verificar o formato e o tamanho do campo."),
	E167("E167", "Município informado não pertence à Unidade Federativa.", "Acerte o município ou a Unidade Federativa."),
	E168("E168", "CEP do tomador do serviço informado indevidamente.", "Não informe o CEP do tomador do serviço quando ele for domiciliado no exterior."),
	E169("E169", "CNPJ/CPF do tomador do serviço informado indevidamente.", "Não informe o CNPJ/CPF do tomador do serviço quando ele for domiciliado no exterior."),
	E17("E17", "A data da emissão do RPS não poderá ser inferior à data de habilitação do prestador do serviço para emissão da NFS-e.", "A geração de NFS-e só é permitida para competência posterior à data de habilitação da empresa."),
	E170("E170", "O usuário não tem autorização para solicitar serviço de processamento de lote de RPS.", "A solicitação de serviço de processamento de lote de RPS só pode ser feita por usuário previamente autorizado pelo contribuinte."),
	E171("E171", "O usuário não tem autorização para assinar  RPS para o prestador de serviço", "Acerte a assinatura do RPS."),
	E172("E172", "Arquivo enviado com erro na assinatura.", "Acerte a assinatura do arquivo."),
	E173("E173", "Lote de RPS não assinado.", "Assine o lote de RPS"),
	E174("E174", "RPS não assinado.", "Assine o  RPS"),
	E175("E175", "O somatório das deduções e do desconto incondicionado está maior que o valor dos serviços", "O preço do serviço deve ser maior ou igual à soma das deduções com o desconto incondicionado."),
	E176("E176", "O somatório dos descontos, retenções federais e ISSQN retido na fonte está maior que o valor dos serviços", "O preço do serviço deve ser maior ou igual à soma dos tributos federais, o ISSQN devido e os descontos."),
	E177("E177", "Pessoa Física não pode efetuar a retenção do ISSQN", "Tomador de serviço pessoa física não pode reter o ISSQN. Altere o indicador de retenção do ISSQN para 2 - sem retenção."),
	E178("E178", "Lote aguardando processamento.", "O lote de RPS correspondente ao protocolo informado foi recebido pela Prefeitura, mas ainda não foi processado."),
	E179("E179", "Erro na autenticação.", "O usuário correspondente ao documento utilizado para autenticação não possui autorização para realizar o serviço para a empresa parametrizada via CNPJ e inscrição municipal do arquivo."),
	E18("E18", "O valor dos serviços deverá ser superior a R$ 0,00 (zero).", "Não é permitido envio de valor de serviços igual a zero."),
	E180("E180", "Pedido de Cancelamento não está assinado.", "O pedido de cancelamento deve conter assinatura digital"),
	E181("E181", "Telefone do tomador do serviço incorreto", "Utilize um telefone no formato válido."),
	E182("E182", "Requisição do serviço não acompanhada de autenticação por certificação digital.", "É necessário efetuar o processo de autenticação SSL bidirecional no sistema cliente."),
	E183("E183", "A mensagem XML do cabeçalho do arquivo enviado está fora do padrão especificado.", "Consulte o Manual da NFS-e para saber quais são as versões de XML Schema suportadas pelo sistema"),
	E184("E184", "A versão de dados não é mais suportada pelo sistema. A versão do XML Schema não é mais suportada pelo sistema.", "Utilize uma versão de dados suportada para requisição dos serviços. Consulte o Manual da NFS-e para saber quais são as versões de XML Schema suportadas pelo sistema"),
	E185("E185", "A versão de dados não existe. A versão do XML Schema não existe.", "Utilize uma versão de dados existente e suportada pelo sistema. Consulte o Manual da NFS-e para saber quais são as versões de XML Schema suportadas pelo sistema"),
	E186("E186", "Requisição de serviço inválida. O sistema não conseguiu capturar o parâmetro nfseCabecMsg e/ou nfseDadosMsg.", "Verifique sua mensagem SOAP e a passagem desses parâmetros necessários. Não conseguiu obter a mensagem XML do cabeçalho ou dos dados. Verifique a passagem desses parâmetros pela mensagem SOAP."),
	E187("E187", "A versão do XML Schema do cabeçalho não existe.", "Consulte o Manual da NFS-e para saber quais são as versões de XML Schema suportadas pelo sistema"),
	E188("E188", "Opção simples nacional conflita com o regime especial de tributação informado.", "Quando se tratar de empresa com Regime Especial de Tributação 05 -  MEI do simples nacional ou  06 - ME ou EPP do simples nacional marcar campo de Optante pelo Simples como 1 – SIM."),
	E189("E189", "Arquivo enviado com erro de certificado. Certificado digital inválido.", "O solicitante do serviço de processamento do arquivo deve utilizar um certificado digital padrão ICP Brasil, não revogado e não expirado."),
	E19("E19", "O valor das deduções deverá ser inferior ou igual ao valor dos serviços.", "Não é permitido valor de dedução superior ao valor de serviços."),
	E190("E190", "Erro na autenticação. Certificado digital inválido.", "O solicitante do serviço de processamento do arquivo deve utilizar um certificado digital padrão ICP Brasil, não revogado e não expirado."),
	E191("E191", "Tipo do RPS inválido.", "Neste município utilizar somente o Tipo 1 - RPS"),
	E192("E192", "Status RPS invalido", "Neste município utilizar somente o Tipo 1 – Normal."),
	E193("E193", "Valor da Retenção do PIS inválido", "O campo referente a retenção do PIS é numérico e deverá ter tamanho máximo 15 números inteiros e dois decimais."),
	E194("E194", "Valor da Retenção da COFINS inválido", "O campo referente a retenção da COFINS é numérico e deverá ter tamanho máximo 15 números inteiros e dois decimais."),
	E195("E195", "Valor da Retenção de INSS inválido", "O campo referente a retenção de INSS é numérico e deverá ter tamanho máximo 15 números inteiros e dois decimais."),
	E196("E196", "Valor da Retenção do IR inválido", "O campo referente a retenção do IR é numérico e deverá ter tamanho máximo 15 números inteiros e dois decimais."),
	E197("E197", "Valor da Retenção da CSLL inválido", "O campo referente a retenção da CSLL é numérico e deverá ter tamanho máximo 15 números inteiros e dois decimais."),
	E198("E198", "Valor das Outras retenções inválido", "O campo referente a outras retenções é numérico e deverá ter tamanho máximo 15 números inteiros e dois decimais."),
	E199("E199", "CEP do tomador do serviço não informado", "Informe o CEP do tomador do serviço"),
	E2("E2", "Data de competência superior a de emissão do RPS.", "Informe uma data de competência inferior ou igual a de emissão do RPS."),
	E20("E20", "O valor das deduções deverá ser superior ou igual a R$ 0,00 (zero).", "Não é permitido valor de dedução inferior a zero (negativo)."),
	E200("E200", "Data de Competência anterior à da autorização para emissão de NFS-e", "A geração de NFS-e só é permitida para competência posterior à data de habilitação da empresa."),
	E201("E201", "Status do RPS não informado", "Informe o status do RPS. Para este município utilizar somente o Tipo 1 – Normal."),
	E202("E202", "Código de tributação não informado", "Informe o código de tributação referente aos serviços prestados"),
	E203("E203", "Tamanho do arquivo enviado excede o permitido.", "Consulte o Manual da NFS-e para saber qual o tamanho de arquivo permitido pelo sistema."),
	E204("E204", "Código de cancelamento não informado.", "Consulte o Manual da NFS-e para saber os códigos de cancelamento permitidos pelo sistema."),
	E205("E205", "Código de cancelamento inválido.", "O campo referente ao cancelamento da NFS-e é numérico e deverá ter tamanho de 4 números inteiros."),
	E206("E206", "Cancelamento da NFS-e por erro na emissão não pode ser feito por esse serviço.", "Utilize o serviço de substituição de NFS-e."),
	E207("E207", "Cancelamento de NFS-e com imposto recolhido não pode ser feito por esse serviço.", "O cancelamento de uma NFS-e com ISSQN pago deverá ser feito por meio de processo administrativo aberto na repartição fazendária."),
	E208("E208", "Cancelamento de NFS-e com tomador do serviço não informado não pode ser feito por esse serviço.", "O cancelamento de uma NFS-e  com tomador do serviço não informado deverá ser feito por meio de processo administrativo aberto na repartição fazendária."),
	E209("E209", "Data inicial não informada", "Informe a data inicial para pesquisa"),
	E21("E21", "O valor dos descontos deverá ser inferior ou igual ao valor dos serviços.", "Não é permitido valor de desconto superior ao valor de serviços."),
	E210("E210", "Data inicial da pesquisa não poderá ser posterior a data de hoje.", "Informe uma data inicial igual ou anterior a data de hoje"),
	E211("E211", "Data inicial da pesquisa não poderá ser posterior a data final.", "Informe uma data inicial igual ou anterior a data final"),
	E212("E212", "NFS-e não encontrada.", "Não existe NFS-e emitida com o número do documento ou do RPS ou período pesquisado."),
	E213("E213", "Código de cancelamento informado de uso exclusivo da Prefeitura", "Código de motivo de cancelamento <3-Erro de assinatura> e <5-Erro de processamento> são de uso exclusivo da Prefeitura."),
	E214("E214", "Número de RPS no lote excede o permitido.", "Consulte o Manual da NFS-e para saber o número máximo de RPS por lote permitido pelo sistema."),
	E215("E215", "Item da lista de serviço incompatível com o código de tributação.", "Consulte o Manual da NFS-e para verificar a correlação entre o código de tributação e o item da lista de serviço.."),
	E216("E216", "Não é permitida a substituição de RPS.", "O campo RpsSubstituido não pode ser preenchido para este município."),
	E217("E217", "Número inicial da faixa de NFS-e não encontrado.", "Informe um número inicial válido."),
	E218("E218", "Número inicial da faixa de NFS-e é maior que o número final.", "Informe um número final maior que o número inicial."),
	E219("E219", "Tipo de Regime Especial de Tributação indevido.", "Consulte o Manual da NFS-e para informar uma opção de  Regime Especial de Tributação valido no município."),
	E22("E22", "O valor dos descontos deverá ser superior ou igual a R$ 0,00 (zero).", "Não é permitido valor de desconto inferior a zero (negativo)."),
	E220("E220", "Valor do ISSQN informado indevidamente.", "O valor do ISSQN será calculado pela Prefeitura e não deve ser informado pelo contribuinte."),
	E221("E221", "Alíquota informada indevidamente.", "A alíquota do ISSQN só deve ser informada quando: o ISSQN for devido a outro município ou o prestador do serviço for optante pelo Simples Nacional e houver retenção do ISSQN. Em outras situações a alíquota a ser aplicada será determinada pela Prefeitura."),
	E222("E222", "Código CNAE informado indevidamente.", "Esse campo não deve ser preenchido neste município."),
	E223("E223", "Intervalo de NFS-e não encontradas.", "Não foram emitidas NFS-e com números no intervalo informado."),
	E224("E224", "A NFS-e a substituir está cancelada.", "NFS-e cancelada não pode ser substituída."),
	E225("E225", "O documento de substituição não está assinado digitalmente.", "Assine o documento de substituição."),
	E226("E226", "Número da NFS-e inicial não informado", "Informe o número da NFS-e inicial do intervalo a ser consultado."),
	E227("E227", "Alíquota Serviços fora do intervalo de 2% e 5%", "Quando o local da incidência for diferente deste município  esse campo deve ser maior ou igual a 2% e menor ou igual a 5%."),
	E228("E228", "Para esta prestação de serviços a alíquota do ISSQN é obrigatória.", "Informe um valor percentual da alíquota de ISSQN, que deve ser maior ou igual a 2% e menor ou igual a 5%."),
	E229("E229", "A Inscrição Municipal do tomador do serviço não existe na base de dados da Prefeitura.", "Informe corretamente a Inscrição Municipal do tomador do serviço."),
	E23("E23", "O valor do PIS deverá ser superior ou igual a R$ 0,00 (zero).", "Não é permitido valor de retenção inferior a zero (negativo)."),
	E230("E230", "As informações do prestador do serviço não foram identificadas no RPS.", "Informe corretamente as informações do prestador do serviço para o RPS."),
	E231("E231", "O prazo legal para conversão de um RPS em NFS-e está expirado.", "Consulte a legislação do município para verificar o prazo de conversão."),
	E232("E232", "Ocorreu um erro no processamento do arquivo.", "Procure a Prefeitura para regularização."),
	E233("E233", "Lote já processado.", "Atribua um novo número ao lote de RPS, caso os RPS nele contidos ainda não tenham sidos processados."),
	E234("E234", "Número do protocolo de recebimento do lote não informado.", "Informe o número do protocolo do lote."),
	E235("E235", "Número da NFS-e a cancelar não informado.", "Informe o número da NFS-e a ser cancelada."),
	E236("E236", "O RPS já está cancelado e não pode ser substituído.", "RPS cancelado não pode ser substituído."),
	E237("E237", "O arquivo de cancelamento de lote de NFS-e está corrompido.", "Corrija e reenvie o arquivo."),
	E238("E238", "O parâmetro nomeado (método) informado não existe", "Consulte o Manual da NFS-e para saber quais são os métodos disponíveis."),
	E239("E239", "Código de tributação não permite dedução na base de cálculo", "Consulte a legislação vigente para saber se o código de tributação permite dedução da base de cálculo"),
	E24("E24", "O valor da COFINS deverá ser superior ou igual a R$ 0,00 (zero).", "Não é permitido valor de retenção inferior a zero (negativo)."),
	E240("E240", "Código de tributação  não permite incidência do ISSQN fora deste município.", "Informe corretamente o município de incidência do ISSQN."),
	E241("E241", "Retenções de Tributos Federais só podem ser efetuados por tomador do serviço pessoa jurídica.", "Preencher os campos de retenções federais com zeros."),
	E242("E242", "Indicador de ISSQN retido incorreto.", "Não é permitida a retenção do ISSQN quando o tomador do serviço é o próprio prestador do serviço. Altere o indicador de retenção do ISSQN devido para 2 - sem retenção."),
	E243("E243", "Esta NFS-e não deverá ter o ISSQN Retido pelo tomador do serviço.", "Consulte a legislação vigente para saber as regras de retenção do ISSQN na fonte e selecione ISS Retido = 2 (NÃO)."),
	E244("E244", "Código de tributação não permite a utilização de NFS-e.", "Consulte a legislação aplicável e verifique os códigos de tributação que permitem a emissão de NFS-e."),
	E245("E245", "Código de tributação não permite desconto condicionado..", "O tipo de serviço prestado não permite desconto condicionado."),
	E246("E246", "Código de tributação não permite desconto incondicionado.", "O tipo de serviço prestado não permite desconto incondicionado."),
	E247("E247", "Código de tributação não permite informação de construção civil.", "Consulte a legislação aplicável e verifique os códigos de tributação que permitem informação de construção civil."),
	E248("E248", "Código de tributação não permite informação de intermediário do serviço.", "Consulte a legislação aplicável e verifique os códigos de tributação que permitem informação  de intermediário do serviço."),
	E25("E25", "O valor do INSS deverá ser superior ou igual a R$ 0,00 (zero).", "Não é permitido valor de retenção inferior a zero (negativo)."),
	E251("E251", "Para o regime especial <Estimativa> não é permitida a emissão de NFS-e", "Consulte a legislação aplicável e verifique as situações de emissão de NFS-e."),
	L107("L107", "Discriminação do serviço inválida.", "Utilize no mínimo 10 caracteres para descrever o serviço prestado."),
	L108("L108", "Não é permitida a Substituição de uma NFS-e sem que tenha sido informado o e-mail do Tomador na emissão.", "Solicite autorização para cancelamento e aguarde o posicionamento da fiscalização."),
	L109("L109", "A NFS-e deve estar emitida para ser cancelada.", "Verifique o status de emissão."),
	L110("L110", "Prazo para Cancelamento ultrapassado.", "Solicite autorização para cancelamento e aguarde o posicionamento da fiscalização."),
	L111("L111", "Não é permitida a Substituição de uma NFS-e Avulsa!", ""),
	L112("L112", "Prazo limite para Substituição expirado.", "Solicite autorização para cancelamento e aguarde o posicionamento da fiscalização."),
	L113("L113", "Contribuinte não autorizado a informar Exigibilidade de ISS ISENÇÃO.", "Corrija o RPS ou proceda a atualização cadastral junto à prefeitura."),
	L114("L114", "Contribuinte não autorizado a informar Exigibilidade de ISS IMUNIDADE.", "Corrija o RPS ou proceda a atualização cadastral junto à prefeitura."),
	L115("L115", "Tomador informado não é substituto tributário e não pode realizar retenção.", "Corrija a nota eletrônica retirando a informação de retenção"),
	L116("L116", "Contribuinte não autorizado a informar Exigibilidade de ISS EXIGIBILIDADE SUSPENSA POR DECISÃO JUDICIAL.", "Corrija o RPS ou efetue o cadastro de uma Decisão Judicial junto à prefeitura."),
	L117("L117", "Contribuinte não autorizado a informar Exigibilidade de ISS EXIGIBILIDADE SUSPENSA POR PROCESSO ADMINISTRATIVO.", "Corrija o RPS ou efetue o cadastro de um Processo Administrativo junto à prefeitura."),
	L118("L118", "Erro na estrutura.", ""),
	L119("L119", "A Exigibilidade está incorreta.", ""),
	L120("L120", "Ao não identificar completamente os dados do Tomador, o cancelamento ou substituição da nota somente poderá ser realizado através de processo administrativo.", "Este cancelamento somente será possível através de processo administrativo"),
	L121("L121", "Consulente não informado, seus dados devem ser iguais ao tomador ou intermediário.", ""),
	L122("L122", "Utilize no máximo 20 linhas para descrever o serviço prestado.", ""),
	L123("L123", "Inscrição municipal do consulente não pode ser maior que 15 dígitos.", ""),
	L125("L125", "CPF/CNPJ do consulente não informado.", ""),
	L126("L126", "CPF/CNPJ do consulente inválido.", ""),
	L127("L127", "CPF/CNPJ do consulente deve ser menor ou igual a 14 e maior ou igual a 11 dígitos.", ""),
	L128("L128", "Tomador possui beneficio fiscal a exigibilidade deve ser.", ""),
	L129("L129", "Número do processo não cadastrado (ou finalizado) para o contribuinte corrente", ""),
	L130("L130", "Contribuinte não possui o benefício.", ""),
	L131("L131", "O processamento síncrono de lote está desativado!", ""),
	L132("L132", "O valor informado na alíquota encontra-se fora do limite estabelecido no benefício da atividade.", ""),
	L133("L133", "Informe o município de emissão da NFS-e.", ""),
	L135("L135", "Lote processado com erros!", ""),
	L137("L137", "O valor da Alíquota deverá ser superior ou igual a 0% (zero).", ""),
	L138("L138", "Para emitir a NFS-e é necessário quitar o débito pendente.", ""),
	L140("L140", "O status da NFS-e é inválido.", ""),
	L141("L141", "Informe a data de emissão da NFS-e.", ""),
	L142("L142", "O debito deve estar quitado para emissão da NFS-e Avulsa.", ""),
	L143("L143", "Não é permitido cancelar uma NFS-e.", ""),
	L144("L144", "Erro ao cancelar a NFS-e", ""),
	L145("L145", "Informe a justificativa do cancelamento da NFS-e.", ""),
	L146("L146", "A justificativa não pode conter mais do que 200 caracteres.", ""),
	L147("L147", "Operação inválida. Só é permitida exclusão de Rascunho de NFS-e.", ""),
	L148("L148", "Já existe uma solicitação de cancelamento para essa NFS-e", ""),
	L149("L149", "Informe a Data do Pedido de Cancelamento.", ""),
	L150("L150", "Informe a justificativa do Pedido de Cancelamento da NFS-e.", ""),
	L151("L151", "Informe o Motivo do Cancelamento.", ""),
	L152("L152", "Selecione a Atividade do Municipio.", ""),
	L153("L153", "O valor de outras retenções deverá ser superior ou igual a 0 (zero).", ""),
	L154("L154", "Emissão de documentos fiscais somente estará disponível após", ""),
	L156("L156", "Informe a atividade realizada no município.", ""),
	L157("L157", "Atividade não autorizada para esse contribuinte.", "Corrija o RPS ou efetue o cadastro do Seviço autorizado para a Atividade 9999 - Outros Serviços.");
	
	private String message;
	private String solucao;
	private String code;
	
	
	private NfsErrorCode(String code, String message, String solucao) {
		this.message = message;
		this.code = code;
		this.solucao = solucao;
	}
	
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}

	public String getSolucao() {
		return solucao;
	}

	public void setSolucao(String solucao) {
		this.solucao = solucao;
	}
	
	
	
	
}
